#!/usr/bin/env bash
################################################################################
# <START METADATA>
# Project Name: QuickBox Pro
# File Name: quickbox_lang_pt
# File Description: Portuguese (Brazil) language file
# File Version: 1.0.47
#
# Save Tasks:
# Automated_Versioning: true
#
# Build Tasks:
# Automated_Comment_Strip: true
#
# Deploy Tasks:
# Automated_Encryption: false
#
# Author: Jason Matthews (JMSolo)
# Author Contact: support@quickbox.io
# Author: Jamie Dobbs (Mschf)
# Author Contact: jamie.dobbs@mschf.dev
#
# License: BSD-3 (Available in LICENSE.md)
# Copyright (C) 2019-2022, QuickBox.IO
# All rights reserved.
# <END METADATA>
# shellcheck disable=2034,2154,2312
################################################################################

quickbox::dashboard::log() {
	admin_name="$(quickbox::database "SELECT username FROM user_information WHERE user_level = '10';")"
	if [[ ! -f "/srv/quickbox/logs/dashboard" ]]; then
		mkdir -p /srv/quickbox/logs
		touch /srv/quickbox/logs/dashboard
		chown www-data:www-data /srv/quickbox/logs/dashboard
	fi
	if [[ ! -f "/srv/quickbox/logs/${username:-${admin_name}}.dashboard" ]]; then
		mkdir -p /srv/quickbox/logs
		touch "/srv/quickbox/logs/${username:-${admin_name}}.dashboard"
		chown www-data:www-data "/srv/quickbox/logs/${username:-${admin_name}}.dashboard"
	fi
	if [[ -n ${username} ]]; then
		echo "${1:-null}" | sed -z "s/\n/\n<br>/" >"/srv/quickbox/logs/${username:-}.dashboard"
	else
		echo "${1:-null}" | sed -z "s/\n/\n<br>/" >"/srv/quickbox/logs/${admin_name:-}.dashboard"
	fi
	echo "${1:-null}"
}
################################################################################
# Clean
################################################################################
quickbox::lang::clean::memory() {
	declare text="memória de limpeza cache..."
	quickbox::dashboard::log "${text}"
}

quickbox::lang::clean::rclone() {
	declare text="registro de upload do rclone de limpeza..."
	quickbox::dashboard::log "${text}"
}

quickbox::lang::clean::rclone::error() {
	declare text="erro: arquivo de log não presente."
	quickbox::dashboard::log "${text}"
}

quickbox::lang::clean::dashboard() {
	declare text="aguardando resposta do sistema"
	quickbox::dashboard::log "${text}"
}
################################################################################
# Locks
################################################################################
quickbox::lang::lock::handle() {
	declare text="${quickbox_lock} está correndo atualmente
o processo será retomado quando ${quickbox_lock} terminar"
	quickbox::dashboard::log "${text}"
}

quickbox::lang::lock::remove() {
	declare text="removendo fechaduras de software..."
	quickbox::dashboard::log "${text}"
}

################################################################################
# Apt
################################################################################
quickbox::lang::apt::update::header() {
	declare text="verificação e execução de atualizações apt..."
	quickbox::dashboard::log "${text}"
}

quickbox::lang::apt::db::locked() {
	declare text="tentando resolver a fechadura dpkg..."
	quickbox::dashboard::log "${text}"
}

quickbox::lang::apt::update::completed() {
	declare text="apt-get upgrade concluído com sucesso"
	quickbox::dashboard::log "${text}"
}

quickbox::lang::apt::check::failed() {
	declare text="apt-get check falhou, você pode ter quebrado pacotes"
	quickbox::dashboard::log "${text}"
}

################################################################################
# Install
################################################################################
quickbox::lang::install::header() {
	declare text="${software_title} será agora instalado
este processo pode levar alguns minutos..."
	quickbox::dashboard::log "${text}"
}

quickbox::lang::install::rutorrent::header() {
	rtorrent_count=$(quickbox::software::count rtorrent)
	if [[ ${rtorrent_count} -eq 0 ]]; then
		declare text="parece que o rTorrent não está instalado

rTorrent 0.9.8 será agora instalado, por favor aguarde
demorar alguns minutos (dependendo das especificações do sistema) para instalar"
	else
		declare text="${software_title} será agora instalado
este processo pode levar alguns minutos..."
	fi
	quickbox::dashboard::log "${text}"
}

quickbox::lang::install::sources::header() {
	declare text="adicionando chaves e fontes adicionais por ${software_title}..."
	quickbox::dashboard::log "${text}"
}

quickbox::lang::install::dependencies::header() {
	declare text="instalando ${software_title} dependências..."
	quickbox::dashboard::log "${text}"
}

quickbox::lang::install::build::header() {
	declare text="construindo ${software_title}..."
	quickbox::dashboard::log "${text}"
}

quickbox::lang::install::mktorrent::header() {
	declare text="construindo mktorrent..."
	quickbox::dashboard::log "${text}"
}

quickbox::lang::install::xmlrpc::header() {
	declare text="construindo xmlrpc-c..."
	quickbox::dashboard::log "${text}"
}

quickbox::lang::install::libtorrent::header() {
	declare text="construindo libtorrent..."
	quickbox::dashboard::log "${text}"
}

quickbox::lang::install::rtorrent::header() {
	declare text="construindo rtorrent..."
	quickbox::dashboard::log "${text}"
}

quickbox::lang::install::configure::header() {
	declare text="configurando ${software_title}..."
	quickbox::dashboard::log "${text}"
}

quickbox::lang::install::backup::header() {
	declare text="backup de ${software_title} configuração..."
	quickbox::dashboard::log "${text}"
}

quickbox::lang::install::start::header() {
	declare text="começando em ${software_title}..."
	quickbox::dashboard::log "${text}"
}

quickbox::lang::install::complete::header() {
	declare text="${software_title} instalação completa"
	quickbox::dashboard::log "${text}"
}

################################################################################
# Reinstall
################################################################################
quickbox::lang::reinstall::header() {
	declare text="${software_title} será reinstalado agora
este processo pode demorar alguns minutos..."
	quickbox::dashboard::log "${text}"
}

quickbox::lang::reinstall::complete::header() {
	declare text="${software_title} reinstalação completa"
	quickbox::dashboard::log "${text}"
}

################################################################################
# Remove
################################################################################
quickbox::lang::remove::header() {
	declare text="${software_title} será agora removido
este processo pode demorar alguns minutos..."
	quickbox::dashboard::log "${text}"
}

quickbox::lang::remove::stop::header() {
	declare text="parando ${software_title}..."
	quickbox::dashboard::log "${text}"
}

quickbox::lang::remove::dependencies::header() {
	declare text="removendo ${software_title} dependências..."
	quickbox::dashboard::log "${text}"
}

quickbox::lang::remove::files::header() {
	declare text="removendo ${software_title} arquivos..."
	quickbox::dashboard::log "${text}"
}

quickbox::lang::remove::complete::header() {
	declare text="${software_title} remoção completa"
	quickbox::dashboard::log "${text}"
}

################################################################################
# Update
################################################################################
quickbox::lang::update::header() {
	declare text="${software_title} será agora atualizado
este processo pode demorar alguns minutos..."
	quickbox::dashboard::log "${text}"
}

quickbox::lang::update::files::header() {
	declare text="atualizando ${software_title}..."
	quickbox::dashboard::log "${text}"
}

quickbox::lang::update::complete::header() {
	declare text="${software_title} atualização completa"
	quickbox::dashboard::log "${text}"
}

################################################################################
# User
################################################################################
quickbox::lang::user::create() {
	declare text="criado pelo usuário do quickbox:"
	quickbox::dashboard::log "${text}"
}

quickbox::lang::user::delete() {
	declare text="${username:-"usuário da quickbox"} apagado"
	quickbox::dashboard::log "${text}"
}

quickbox::lang::user::username() {
	declare text="usuário: ${username}"
	quickbox::dashboard::log "${text}"
}

quickbox::lang::user::password() {
	declare text="senha: ${password}"
	quickbox::dashboard::log "${text}"
}

quickbox::lang::user::password::updated() {
	declare text="senha do ${username:-"usuário da quickbox"} atualizada"
	quickbox::dashboard::log "${text}"
}

quickbox::lang::user::ban() {
	declare text="${username:-"usuário da quickbox"} banido"
	quickbox::dashboard::log "${text}"
}

quickbox::lang::user::unban() {
	declare text="${username:-"usuário da quickbox"} não-distribuído"
	quickbox::dashboard::log "${text}"
}

quickbox::lang::user::demote() {
	declare text="${username:-"usuário da quickbox"} despromovido de admin"
	quickbox::dashboard::log "${text}"
}

quickbox::lang::user::promote() {
	declare text="${username:-"usuário da quickbox"} promovido à admin"
	quickbox::dashboard::log "${text}"
}

################################################################################
# Misc
################################################################################
quickbox::lang::username::specified() {
	declare text="erro: nome de usuário não especificado"
	quickbox::dashboard::log "${text}"
}

quickbox::lang::software::info::example() {
	if [[ ${process} == "install" ]]; then
		[[ -n ${usr} ]] && declare text="qb ${process} ${software_name} -u usuário ${option[*]}"
		[[ -n ${dmn} ]] && declare text="qb ${process} ${software_name} -d somedomain.com ${option[*]}"
		[[ -n ${usr} && -n ${dmn} ]] && declare text="qb ${process} ${software_name} -u usuário -d somedomain.com ${option[*]}"
		[[ -z ${usr} && -z ${dmn} ]] && declare text="qb ${process} ${software_name} ${option[*]}"
	elif [[ ${process} == "reinstall" ]]; then
		[[ -n ${usr} ]] && declare text="qb ${process} ${software_name} -u usuário ${option[*]}"
		[[ -n ${dmn} ]] && declare text="qb ${process} ${software_name} -d somedomain.com ${option[*]}"
		[[ -n ${usr} && -n ${dmn} ]] && declare text="qb ${process} ${software_name} -u usuário -d somedomain.com ${option[*]}"
		[[ -z ${usr} && -z ${dmn} ]] && declare text="qb ${process} ${software_name} ${option[*]}"
	elif [[ ${process} == "remove" ]]; then
		[[ -n ${usr} ]] && declare text="qb ${process} ${software_name} -u usuário ${option[*]}"
		[[ -n ${dmn} ]] && declare text="qb ${process} ${software_name} -d somedomain.com ${option[*]}"
		[[ -z ${usr} && -z ${dmn} ]] && declare text="qb ${process} ${software_name} ${option[*]}"
	elif [[ ${process} == "update" ]]; then
		[[ -n ${usr} ]] && declare text="qb ${process} ${software_name} -u usuário ${option[*]}"
		[[ -n ${dmn} ]] && declare text="qb ${process} ${software_name} -d somedomain.com ${option[*]}"
		[[ -z ${usr} && -z ${dmn} ]] && declare text="qb ${process} ${software_name} ${option[*]}"
	fi
	quickbox::dashboard::log "${text}"
}

quickbox::lang::software::info::note() {
	[[ ${software_name} == "radarr" && ${is4k} == 1 ]] && declare software_name="radarr4k"
	[[ ${software_name} == "sonarr" && ${is4k} == 1 ]] && declare software_name="sonarr4k"
	if [[ ${process} == "install" ]]; then
		[[ -n ${usr} ]] && declare text="instala a versão mais recente do ${branch} do ${software_name} para o usuário"
		[[ -n ${dmn} ]] && declare text="instala um certificado SSL a ser usado para o painel no domínio especificado"
		[[ -n ${usr} && -n ${dmn} ]] && declare text="instala a versão mais recente do ${branch} do ${software_name} para o usuário e prepara o certificado SSL para o domínio"
		[[ -n ${no-dash} && -z ${usr} && -z ${dmn} && -z ${version} ]] && declare text="instala um certificado SSL para o domínio especificado"
		[[ -n ${version} ]] && declare text="instala a versão ${version[*]} mais recente de ${software_name}"
		[[ -n ${branch} && -z ${usr} ]] && declare text="instala a versão mais recente de ${branch} de ${software_name}"
	elif [[ ${process} == "reinstall" ]]; then
		[[ -n ${usr} ]] && declare text="reinstala a versão mais recente do ${branch} de ${software_name} para o usuário"
		[[ -n ${dmn} ]] && declare text="reinstala o certificado SSL usado para o painel no domínio especificado"
		[[ -n ${usr} && -n ${dmn} ]] && declare text="reinstala a versão mais recente do ${branch} do ${software_name} para o usuário e prepara o certificado SSL para o domínio"
		[[ -n ${no-dash} && -z ${usr} && -z ${dmn} && -z ${version} ]] && declare text="reinstala um certificado SSL para o domínio especificado"
		[[ -n ${version} ]] && declare text="reinstala a versão ${version[*]} mais recente de ${software_name}"
		[[ -n ${branch} && -z ${usr} ]] && declare text="instala a versão mais recente de ${branch} de ${software_name}"
	elif [[ ${process} == "remove" ]]; then
		[[ -n ${usr} ]] && declare text="remover ${software_name} para usuário"
		[[ -n ${dmn} && -z ${usr} && -z ${version} ]] && declare text="remover o certificado SSL do domínio especificado"
		[[ -n ${version} && -z ${dmn} ]] && declare text="remover ${software_name}"
		[[ -z ${usr} && -z ${version} && -z ${dmn} ]] && declare text="remover ${software_name}"
	elif [[ ${process} == "update" ]]; then
		[[ -n ${usr} ]] && declare text="atualiza ${software_name} para a versão mais recente do ${branch} para o usuário"
		[[ -n ${dmn} ]] && declare text="atualiza o certificado SSL para o domínio especificado, a ser usado com o painel"
		[[ -n ${no-dash} && -z ${usr} && -z ${dmn} && -z ${version} ]] && declare text="atualiza o certificado SSL para o domínio especificado"
		[[ -n ${version} ]] && declare text="atualiza ${software_name} para a versão ${version} mais recente"
		[[ -n ${branch} && -z ${usr} ]] && declare text="instala a versão mais recente de ${branch} de ${software_name}"
	fi
	quickbox::dashboard::log "${text}"
}

quickbox::lang::software::access() {
	declare text="acesse ${software_title} em:
${quickbox_web_root}${software_name}
${software_title} instalado na porta: ${software_web_port}"
	quickbox::dashboard::log "${text}"
}

quickbox::lang::software::mu::access() {
	declare text="acesse ${software_title} em:
${quickbox_web_root}${username}/${software_name}
${software_title} instalado na porta: ${software_web_port}"
	quickbox::dashboard::log "${text}"
}

quickbox::lang::software::calibre::access() {
	declare text="acesse ${software_title} em:
${quickbox_web_root}${username}/${software_name}
nome de usuário: ${username}
senha: admin123
localização do banco de dados: /home/${username}/.config/calibre/library
${software_title} instalado na porta: ${software_web_port}"
	quickbox::dashboard::log "${text}"
}

quickbox::lang::software::rtorrent::access() {
	declare text="> versão rTorrent: ${rtorrent_version}
> versão libtorrent: ${libtorrent_version}
> caminho do soquete: /var/run/${admin_name}/.rtorrent.sock"
	quickbox::dashboard::log "${text}"
}

quickbox::lang::software::rutorrent::access() {
	declare text="acesse ${software_title} em:
${quickbox_web_root}${software_name}
> caminho do soquete: /var/run/${admin_name}/.rtorrent.sock"
	quickbox::dashboard::log "${text}"
}

quickbox::lang::software::admin::access() {
	declare text="acesse ${software_title} em:
${quickbox_web_root}${admin_name}/${software_name}
${software_title} instalado na porta: ${software_web_port}"
	quickbox::dashboard::log "${text}"
}

quickbox::lang::software::dashboard() {
	declare text="domínio: https://${domain}/"
	quickbox::dashboard::log "${text}"
}

quickbox::lang::software::dashboard::custom() {
	declare text="ssl certificado por ${domain} instalado para:
/etc/nginx/ssl/${domain}/"
	quickbox::dashboard::log "${text}"
}

quickbox::lang::database() {
	declare text="atualizando o banco de dados..."
	quickbox::dashboard::log "${text}"
}

quickbox::lang::trackers::disable() {
	declare text="desativando rastreadores públicos..."
	quickbox::dashboard::log "${text}"
}

quickbox::lang::trackers::enable() {
	declare text="possibilitando rastreadores públicos..."
	quickbox::dashboard::log "${text}"
}
quickbox::lang::directory::noexist() {
	declare text="diretório necessário não existe..."
	quickbox::dashboard::log "${text}"
}

quickbox::lang::directory::nomove() {
	declare text="incapaz de passar para $1..."
	quickbox::dashboard::log "${text}"
}
quickbox::lang::package::fail() {
	declare text="não pôde instalar um pacote necessário $1..."
	quickbox::dashboard::log "${text}"
}

quickbox::lang::software::flaresolverr::access() {
	curl_check=$(curl -s "127.0.0.1:${software_web_port}" | grep -o "FlareSolverr is ready!")
	if [[ ${curl_check} == "FlareSolverr is ready!" ]]; then
		declare text="status: ok. FlareSolverr está pronto!
${software_title} instalado na porta: ${software_web_port}"
		quickbox::dashboard::log "${text}"
	else
		declare text="Parece que algo deu errado"
		quickbox::dashboard::log "${text}"
	fi
}

quickbox::lang::software::plexclaim() {
	declare text="reivindicando servidor plex para ${username}..."
	quickbox::dashboard::log "${text}"
}

quickbox::lang::software::plex::access() {
	declare text="acesse ${software_title} em:
${quickbox_web_root}web/
${software_title} instalado na porta: ${software_web_port}

> se ainda não o fez, ou se não tem a certeza de como 
reclamar o seu servidor plex por favor siga este guia:
https://quickbox.io/kb-categories/plex/"
	quickbox::dashboard::log "${text}"
}

quickbox::lang::software::plexupdate_credentials_header() {
	declare text="Por favor, digite suas credenciais Plex (Nome de usuário/Senha/2FA):"
	quickbox::dashboard::log "${text}"
}

quickbox::lang::software::plexupdate_credentials_subheader() {
	declare text="Estas credenciais não serão salvas ou compartilhadas fora desta instância."
	quickbox::dashboard::log "${text}"
}

quickbox::lang::software::plexupdate_credentials_email() {
	declare text="Email: "
	quickbox::painel::log "${text}"
}

quickbox::lang::software::plexupdate_credentials_password() {
	declare text="Senha: "
	quickbox::dashboard::log "${text}"
}

quickbox::lang::software::plexupdate_credentials_otp() {
	declare text="2FA: [Deixar em branco se não houver conjunto 2FA] "
	quickbox::painel::log "${text}"
}

quickbox::lang::software::plexupdate_credentials_fail() {
	declare text="O nome de usuário e a senha são necessários para fazer o download da atualização do PlexPass."
	quickbox::dashboard::log "${text}"
}

quickbox::lang::software::plexupdate_credentials_incorrect() {
	declarar text="Nome de usuário e/ou senha incorretos"
	quickbox::painel::log "${text}"
}

quickbox::lang::software::plexupdate_credentials_loginfail() {
	declare text="Falha no login, depuração de informações:"
	quickbox::painel::log "${text}"
}

quickbox::lang::software::plexupdate_credentials_retrievefail() {
	declare text="Incapaz de recuperar a URL de download."
	quickbox::dashboard::log "${text}"
}

quickbox::lang::software::plexupdate_credentials_parsefail() {
	declare text="Falha na análise da resposta HTML."
	quickbox::dashboard::log "${text}"
}

quickbox::lang::software::plexupdate_downloading() {
	declare text="Fazendo o download da atualização do Plex..."
	quickbox::painel::log "${text}"
}

quickbox::lang::software::plexupdate_downloading_fail() {
	declare text="O download falhou com código de erro ${code}, ${error}"
	quickbox::painel::log "${text}"
}

quickbox::lang::software::plexupdate_installing() {
	declare text="Instalando a nova versão do Plex..."
	quickbox::dashboard::log "${text}"
}

quickbox::lang::software::plexupdate_updated() {
	declare text="O Plex foi atualizado com sucesso."
	quickbox::dashboard::log "${text}"
}

quickbox::lang::software::plexupdate_current() {
	declare text="Plex já está em dia."
	quickbox::dashboard::log "${text}"
}

quickbox::lang::software::pyload::access() {
	declare text="acesse ${software_title} em:
${quickbox_web_root}${username}/${software_name}/
${software_title} instalado na porta: ${software_web_port}

> nome de usuário = ${username}
> senha = pyload

> Login para fazer o pyload e alterar a senha padrão de segurança.
Sua senha pode ser alterada sob a guia [usuários] em pyload."
	quickbox::dashboard::log "${text}"
}

quickbox::lang::software::quassel::access() {
	server_ip=$(ip route get 8.8.8.8 | sed -n '/src/{s/.*src *\([^ ]*\).*/\1/p;q}')
	declare text="${software_title} instalado na porta: ${software_daemon_port}
  
> Por favor, instale o quassel-cliente em seu cliente pessoal 
computador e conecte-se ao recém-criado ${software_title} Núcleo 
para configurar sua conta em:
${server_ip}:${software_daemon_port}

> Baixar quassel-cliente a partir do seguinte:
https://quassel-irc.org/downloads"
	quickbox::dashboard::log "${text}"
}

quickbox::lang::software::rclone_configure() {
	declare text="
Por favor, visite https://console.developers.google.com e crie um projeto.
Você precisará tomar nota de seu client_id e client_secret.
Você também pode visitar o artigo abaixo da Base de Conhecimento para uma caminhada:
https://quickbox.io/knowledge-base/creating-a-google-api-client-id-client-secret-code/

Uma vez que você tenha tanto seu client_id quanto client_secret, pressione qualquer tecla para continuar.

"
	quickbox::dashboard::log "${text}"
}
quickbox::lang::software::rclone_entries() {
	declare text="Digite abaixo os detalhes de sua conexão."
	quickbox::dashboard::log "${text}"
}
quickbox::lang::software::rclone_clientid() {
	declare text="Identificação do cliente: "
	quickbox::dashboard::log "${text}"
}
quickbox::lang::software::rclone_clientsecret() {
	declare text="Segredo do cliente: "
	quickbox::dashboard::log "${text}"
}
quickbox::lang::software::rclone_encryptpass() {
	declare text="Senha de encriptação: "
	quickbox::dashboard::log "${text}"
}
quickbox::lang::software::rclone_saltpass() {
	declare text="Senha de sal: "
	quickbox::dashboard::log "${text}"
}
quickbox::lang::software::rclone_salterror() {
	declare text="A senha de sal não pode ser a mesma que a senha de criptografia."
	quickbox::dashboard::log "${text}"
}
quickbox::lang::software::rclone_confirm() {
	declare text="Favor confirmar os seguintes detalhes antes de continuar..."
	quickbox::dashboard::log "${text}"
}
quickbox::lang::software::rclone_clientid_confirm() {
	declare text="Identificação do cliente: ${clientvar}"
	quickbox::dashboard::log "${text}"
}
quickbox::lang::software::rclone_clientsecret_confirm() {
	declare text="Segredo do cliente: ${secretvar}"
	quickbox::dashboard::log "${text}"
}
quickbox::lang::software::rclone_encryptpass_confirm() {
	declare text="Senha de encriptação: ${encvar}"
	quickbox::dashboard::log "${text}"
}
quickbox::lang::software::rclone_saltpass_confirm() {
	declare text="Senha de sal: ${saltvar}"
	quickbox::dashboard::log "${text}"
}
quickbox::lang::software::rclone_continue() {
	declare text="Se estiver satisfeito com os ajustes acima, pressione Y para continuar..."
	quickbox::dashboard::log "${text}"
}
quickbox::lang::software::rclone::access() {
	declare text="${software_title} instalado
  
> Execute o seguinte comando para finalizar a configuração:
runuser -l ${username} -c \"rclone config reconnect gdrive:\"

> Para obter mais informações sobre como instalar o rclone, visite:
https://quickbox.io/knowledge-base/applications/rclone/how-to-install-rclone/
"
	quickbox::dashboard::log "${text}"
}

quickbox::lang::software::x2go::access() {
	server_ip=$(ip route get 8.8.8.8 | sed -n '/src/{s/.*src *\([^ ]*\).*/\1/p;q}')
	declare text="${software_title} Servidor instalado
  
> Instale o x2go-client em seu computador pessoal
e conecte-se ao servidor ${software_title} recém-criado
usando o seguinte:
Anfitrião:			${server_ip}
Login:				${username}
Porta SSH:			4747
Tipo de sessão:		XFCE ou MATE

> Faça o download do x2go-client a partir do seguinte:
https://wiki.x2go.org/doku.php/doc:installation:x2goclient"
	quickbox::dashboard::log "${text}"
}

quickbox::lang::software::znc_configure() {
	declare text="A configuração ZNC será executada agora. Por favor, responda as seguintes perguntas:"
	quickbox::dashboard::log "${text}"
}

################################################################################
# QB Updater
################################################################################
quickbox::lang::update::ntp() {
	declare text="verificando com o servidor ntp..."
	quickbox::dashboard::log "${text}"
}

quickbox::lang::update::apt() {
	declare text="executando atualizações do apt..."
	quickbox::dashboard::log "${text}"
}

quickbox::lang::update::initial::dependencies() {
	declare text="verificando as dependências iniciais..."
	quickbox::dashboard::log "${text}"
}

quickbox::lang::update::download::v3() {
	declare text="baixando atualização v3..."
	quickbox::dashboard::log "${text}"
}

quickbox::lang::update::quickbox::dependencies() {
	declare text="verificando as dependências do quickbox..."
	quickbox::dashboard::log "${text}"
}

quickbox::lang::update::base::dependencies() {
	declare text="instalando dependências de base: "
	quickbox::dashboard::log "${text}"
}

quickbox::lang::update::web::dependencies() {
	declare text="instalando dependências da web: "
	quickbox::dashboard::log "${text}"
}

quickbox::lang::update::python::dependencies() {
	declare text="instalando dependências python: "
	quickbox::dashboard::log "${text}"
}

quickbox::lang::update::dependencies::log() {
	declare text="salvando dependências instaladas..."
	quickbox::dashboard::log "${text}"
}

quickbox::lang::update::pip() {
	declare text="atualizando pip..."
	quickbox::dashboard::log "${text}"
}

quickbox::lang::update::lshell() {
	declare text="atualizando lshell..."
	quickbox::dashboard::log "${text}"
}

quickbox::lang::update::iris() {
	declare text="atualizando íris..."
	quickbox::dashboard::log "${text}"
}

quickbox::lang::update::libraries() {
	declare text="atualizando bibliotecas quickbox..."
	quickbox::dashboard::log "${text}"
}

quickbox::lang::update::cron() {
	declare text="atualizando cron jobs..."
	quickbox::dashboard::log "${text}"
}

quickbox::lang::update::sudo() {
	declare text="atualizando as configurações do sudo..."
	quickbox::dashboard::log "${text}"
}

quickbox::lang::update::curl() {
	declare text="atualizando curl..."
	quickbox::dashboard::log "${text}"
}

quickbox::lang::update::php::check() {
	declare text="verificando php..."
	quickbox::dashboard::log "${text}"
}

quickbox::lang::update::qbcommands() {
	declare text="configurando comandos do quickbox pro..."
	quickbox::dashboard::log "${text}"
}

quickbox::lang::update::dashboard() {
	declare text="atualizando o painel do quickbox..."
	quickbox::dashboard::log "${text}"
}

quickbox::lang::update::database() {
	declare text="atualizando banco de dados quickbox..."
	quickbox::dashboard::log "${text}"
}

quickbox::lang::update::autocomplete() {
	declare text="atualizando o preenchimento automático do quickbox..."
	quickbox::dashboard::log "${text}"
}

quickbox::lang::update::permissions() {
	declare text="configurando permissões..."
	quickbox::dashboard::log "${text}"
}

quickbox::lang::update::clean() {
	declare text="limpando arquivos de atualização..."
	quickbox::dashboard::log "${text}"
}

quickbox::lang::update::complete() {
	declare text="atualização concluída!"
	quickbox::dashboard::log "${text}"
}
